packages:
  - apps/*
  - packages/*

catalog:
  '@fluentui/react-components': ^9.74.7
  '@fluentui/react-icons': ^2.0.339
  '@types/node': 24.10.1
  typescript: 6.0.3
  vite: 7.3.6
  vitest: 4.1.10

catalogMode: strict

cleanupUnusedCatalogs: true

linkWorkspacePackages: true

allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  deno: true
  electron: true
  electron-winstaller: true
  esbuild: true
  sharp: true

saveWorkspaceProtocol: rolling

sharedWorkspaceLockfile: true
